---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp music.html $DEPLOYPATH
    - /bin/cp merch.html $DEPLOYPATH
    - /bin/cp -R css.html $DEPLOYPATH
    - /bin/cp -R img.css $DEPLOYPATH
